### ISSUE TITLE
 NaN prediction  value after some epochs ??

### ISSUE THREAD

**Issue by navalkishoremehta95** [KevinDuarte/VideoCapsuleNet#12]
Hi , 
I am training the network as multi-class classification model (spiked segmentation part ) on some video dateset. After some epochs it is showing 'nan' prediction value. what could be the problem ?
 lr = 0.001
![Screenshot from 2021-02-11 11-29-49](https://user-images.githubusercontent.com/6260545/107606569-817a5080-6c5c-11eb-9dc3-15de4c89e8bc.png)

**Comment by KevinDuarte** [comment]
This issue usually occurs due to instability in the routing operation. I have changed the em-routing algorithm to include an epsilon term in a couple of operations which could cause some instability.

If the issue still persists after this change, I would suggest decreasing the inv_temp and inv_temp_delta variables, which usually reduces instability (but may effect training time).
